global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
- target_matchers:
  - alertname = InfoInhibitor
receivers:
- name: "null"
- name: 'nginx down'
  discord_configs:
    - webhook_url: 'https://discord.com/api/webhooks/13'
route:
  group_by:
  - namespace
  group_interval: 1s
  group_wait: 1m
  receiver: "null"
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname = "Watchdog"
    receiver: "null"
  - matchers:
    - alertname = "nginx down"
    receiver: "nginx down"
templates:
- /etc/alertmanager/config/*.tmpl