apiVersion: v1
kind: Service
metadata:
 name: nginx-server
 labels:
   job: nginx
   service: nginx
spec:
 type: NodePort
 ports:
 - name: web
   targetPort: 80
   port: 8080
   nodePort: 30008
 selector:
   app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    service: nginx-exporter
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 30013
  selector:
    app: nginx
