apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
        items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-exporter
  labels:
    app: nginx-exporter
spec:
  containers:
    - name: nginx-exporter
      image: 'nginx/nginx-prometheus-exporter'
      args:
        - '-nginx.scrape-uri=http://nginx-server/nginx_status'
      ports:
        - containerPort: 9113
