apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      service: nginx-exporter
  endpoints:
    - port: metrics
      interval: 5s
