kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30909 # The port of the prometheus process running
    hostPort: 9090 # The host port you want to expose the k8s service
    protocol: TCP
  - containerPort: 30910 # The port of the node-exporter process running
    hostPort: 9100 # The host port you want to expose the k8s service
    protocol: TCP
- role: worker
